### ISSUE TITLE
change incrementing to timestamp

### ISSUE THREAD

**Issue by DenysBorysenko1** [TimMikeladze/arango-migrate#81]
We use your package in a large development team
  we have problems with increment names (in parallel, several developers can create different migrations with the same numbers)
It makes sense to change the name to timestamps

**Comment by TimMikeladze** [comment]
Interesting feedback and makes total sense. Thanks. 

I'll see about implementing this but can't guarantee it'll be immediately. Will definitely try to get to it by the end of the month. 

Open for PRs of course.

**Comment by TimMikeladze** [comment]
This has been implemented by @mrkuzzmin in #96.
